version: '3'
services:
  fe:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_BASE_SERVER_URL=http://localhost:3333
    volumes:
      - ./:/usr/src/app/